### Numpy Arrays Operations

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Silicing", arr[2:7])
print("With Steps Silcing", arr[1:10:2])
print("Negative index", arr[-3])


Basic Silicing [3 4 5 6 7]
With Steps Silcing [ 2  4  6  8 10]
Negative index 8


## In 2D Arrays

In [14]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])
print("Specific Element:", arr2d[1,2])
print("Row wise:", arr2d[1])
print("Colum wise:", arr2d[:,1])


Specific Element: 6
Row wise: [4 5 6]
Colum wise: [2 5]


### Sorting In Array

In [21]:
unsorted_arr = np.array([1,2,3,43,25,4,6,10])
print("Sorted:", np.sort(unsorted_arr))


#In 2D array
arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted:", np.sort(arr_2D_unsorted,axis = 1))

Sorted: [ 1  2  3  4  6 10 25 43]
Sorted: [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [23]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

# Filter with mask
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

[ 2  4  6  8 10]
Numbers greater than 5 [ 6  7  8  9 10]


### Fncy indexing vs np.where

In [29]:
indices = [0 ,2, 4]
print(numbers[indices])
where_result = np.where(numbers > 5)
print("NP where",where_result)

# condition_array
condition_array = np.where(numbers >5 , numbers *4, numbers)
print(condition_array)

[1 3 5]
NP where (array([5, 6, 7, 8, 9]),)
[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing Data

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1 , arr2))
print(combined)


# Compatibility

a = np.array([1,2,3])
b = np.array([4,5,6])
print("Combined shapes:", a.shape == b.shape)


[1 2 3 4 5 6]
Combined shapes: True


## vstack and hstack

In [37]:
orginal = np.array([[1,2],
                    [3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((orginal, new_row))
print(with_new_row)

new_col = np.array([[7] ,[8]])
with_new_col = np.hstack((orginal, new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


### Deleting

In [39]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 3)
print(deleted)

[1 2 3 5]
