##Numpy tutorial

In [2]:
import numpy as np

# Creating Array from List

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:" ,arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: ", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 5 6]]


## List VS numpy Array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("Python List Multiplication by 2:", py_list * 2)

np_array = np.array([1,2,3])
print("Numpy Array Multiplication by 2:", np_array * 2)

import time 
# Time taken by Python List
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation took: ", time.time() - start)

# Time taken by Numpy Array
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation took: ", time.time() - start)


Python List Multiplication by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array Multiplication by 2: [2 4 6]

 List operation took:  0.1170804500579834

 Numpy operation took:  0.02157449722290039


## Creating Array from Scratch

In [5]:
zeros = np.zeros((3,3))
print("Array of Zeros:\n,", zeros)

ones = np.ones((3,3))
print("Array of Ones:\n", ones)

full = np.full((2,3) , 4)
print("Array of Contants\n" , full)

random = np.random.random((3,3))
print("Array of Random\n", random)

sequence = np.arange(0 , 11 , 2)
print("Array of a Sequence\n", sequence)





Array of Zeros:
, [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of Contants
 [[4 4 4]
 [4 4 4]]
Array of Random
 [[0.27219834 0.27107412 0.94051097]
 [0.81379247 0.74565771 0.45159172]
 [0.99386268 0.5064106  0.20273947]]
Array of a Sequence
 [ 0  2  4  6  8 10]


### Vector , Matrix , Tensor

In [6]:
vector = np.array([1,2,3])
print(vector)

Matrix = np.array([[1,2,3],
                   [4,5,6]])
print(Matrix)

tensor = np.array([[[1,2] , [3,4]], [[5,6], [7,8]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [7]:
arr = np.array([[2,3,4],
                 [3,4,5]])

print("Shape\n", arr.shape)
print("Dimension\n", arr.ndim)
print("size\n", arr.size)
print("Data Type\n", arr.dtype)

Shape
 (2, 3)
Dimension
 2
size
 6
Data Type
 int64


### Arrays Reshaping


In [8]:
arr = np.arange(12)
print("Original Array: \n",arr)

reshape =   arr.reshape(3,4)
print(reshape)

flattened = reshape.flatten()
print(flattened)

# return views instead of copy
raveled = reshape.ravel()
print(raveled)

#Returns transpose of a MAtrix
transpose = reshape.T
print(transpose)


Original Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
